// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	User
	RegisterRequest
	RegisterResponse
	LoginRequest
	LoginResponse
	ValidateRequest
	ValidateResponse
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Permissions int32

const (
	Permissions_USER  Permissions = 0
	Permissions_ADMIN Permissions = 1
)

var Permissions_name = map[int32]string{
	0: "USER",
	1: "ADMIN",
}
var Permissions_value = map[string]int32{
	"USER":  0,
	"ADMIN": 1,
}

func (x Permissions) String() string {
	return proto.EnumName(Permissions_name, int32(x))
}
func (Permissions) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type User struct {
	Uuid        string      `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Email       string      `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	FirstName   string      `protobuf:"bytes,3,opt,name=firstName" json:"firstName,omitempty"`
	LastName    string      `protobuf:"bytes,4,opt,name=lastName" json:"lastName,omitempty"`
	Permissions Permissions `protobuf:"varint,5,opt,name=permissions,enum=Permissions" json:"permissions,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetPermissions() Permissions {
	if m != nil {
		return m.Permissions
	}
	return Permissions_USER
}

type RegisterRequest struct {
	Password string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type LoginRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *ValidateRequest) Reset()                    { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string            { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()               {}
func (*ValidateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ValidateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *ValidateResponse) Reset()                    { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string            { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()               {}
func (*ValidateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ValidateResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*ValidateRequest)(nil), "ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "ValidateResponse")
	proto.RegisterEnum("Permissions", Permissions_name, Permissions_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := grpc.Invoke(ctx, "/Auth/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/Auth/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := grpc.Invoke(ctx, "/Auth/Validate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Auth_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Auth_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x4b, 0xeb, 0x40,
	0x14, 0xc5, 0x33, 0x7d, 0xc9, 0xa3, 0xbd, 0xfd, 0x97, 0x5e, 0xde, 0x22, 0x2f, 0xb8, 0x28, 0x03,
	0x62, 0x11, 0x3a, 0x60, 0xfd, 0x02, 0x16, 0x74, 0x21, 0x68, 0x91, 0x48, 0xdd, 0x8f, 0x74, 0x6c,
	0x07, 0xdb, 0x4c, 0x9c, 0x99, 0xe0, 0x37, 0x71, 0xe1, 0xa7, 0x95, 0x4c, 0x9b, 0x26, 0x46, 0x77,
	0xb9, 0xe7, 0x9e, 0xfc, 0x32, 0xe7, 0x64, 0x00, 0x78, 0x6e, 0x37, 0x2c, 0xd3, 0xca, 0x2a, 0xfa,
	0x49, 0xc0, 0x5f, 0x1a, 0xa1, 0x11, 0xc1, 0xcf, 0x73, 0xb9, 0x8a, 0xc8, 0x98, 0x4c, 0x3a, 0x89,
	0x7b, 0xc6, 0x7f, 0x10, 0x88, 0x1d, 0x97, 0xdb, 0xa8, 0xe5, 0xc4, 0xfd, 0x80, 0x27, 0xd0, 0x79,
	0x91, 0xda, 0xd8, 0x05, 0xdf, 0x89, 0xe8, 0x8f, 0xdb, 0x54, 0x02, 0xc6, 0xd0, 0xde, 0xf2, 0xc3,
	0xd2, 0x77, 0xcb, 0xe3, 0x8c, 0x0c, 0xba, 0x99, 0xd0, 0x3b, 0x69, 0x8c, 0x54, 0xa9, 0x89, 0x82,
	0x31, 0x99, 0x0c, 0x66, 0x3d, 0xf6, 0x50, 0x69, 0x49, 0xdd, 0x40, 0xa7, 0x30, 0x4c, 0xc4, 0x5a,
	0x1a, 0x2b, 0x74, 0x22, 0xde, 0x72, 0x61, 0x6c, 0x81, 0xcf, 0xb8, 0x31, 0xef, 0x4a, 0x97, 0x47,
	0x3d, 0xce, 0x14, 0x21, 0xac, 0xec, 0x26, 0x53, 0xa9, 0x11, 0xf4, 0x0a, 0x7a, 0x77, 0x6a, 0x2d,
	0xd3, 0xf2, 0xfd, 0x63, 0x24, 0x52, 0x8f, 0x54, 0xa7, 0xb6, 0x1a, 0xd4, 0x53, 0xe8, 0x1f, 0x08,
	0x7b, 0x64, 0x81, 0xb0, 0xea, 0x55, 0xa4, 0x25, 0xc2, 0x0d, 0xf4, 0x0c, 0x86, 0x4f, 0x7c, 0x2b,
	0x57, 0xdc, 0x8a, 0xda, 0xb7, 0x7e, 0x31, 0x4e, 0x21, 0xac, 0x8c, 0x07, 0xe4, 0x7f, 0xf0, 0x73,
	0x23, 0xb4, 0x33, 0x76, 0x67, 0x01, 0x2b, 0xfe, 0x48, 0xe2, 0xa4, 0x73, 0x0a, 0xdd, 0x5a, 0x3f,
	0xd8, 0x06, 0x7f, 0xf9, 0x78, 0x93, 0x84, 0x1e, 0x76, 0x20, 0x98, 0x5f, 0xdf, 0xdf, 0x2e, 0x42,
	0x32, 0xfb, 0x20, 0xe0, 0xcf, 0x73, 0xbb, 0xc1, 0x0b, 0x68, 0x97, 0x0d, 0x60, 0xc8, 0x1a, 0xdd,
	0xc5, 0x23, 0xf6, 0xa3, 0x1e, 0x0f, 0x27, 0x10, 0xb8, 0x78, 0xd8, 0x67, 0xf5, 0xa2, 0xe2, 0x01,
	0xfb, 0x96, 0x9a, 0x7a, 0x05, 0xbc, 0x3c, 0x38, 0x86, 0xac, 0x11, 0x36, 0x1e, 0xb1, 0x66, 0x2a,
	0xea, 0x3d, 0xff, 0x75, 0x97, 0xec, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xde, 0xd9, 0x0f, 0xea,
	0x72, 0x02, 0x00, 0x00,
}
